### ISSUE TITLE
Interne PHP package

### ISSUE THREAD

**Issue by xewl** [josbeir/shopwedo-php-api#2]
Sinds enige tijd heeft SWD een interne PHP-package, te vinden op: https://bitbucket.org/shopwedo/shopwedo-api-php
( meer info op de [documentatie](https://admin.shopwedo.com/developer/) zelf )

Sinds April '23 lijkt ook de hostname opnieuw veranderd te zijn.

> kwestie om onze mede-devs die op deze repository landen te informeren.

**Comment by josbeir** [comment]
Thanks, updated to Readme to link to the new package.
